# Site settings
title: "Kaye"
description: "Learn English - Hire a private English Tutor today!"
author: "Kinah Watts"
email: "iammisskaye00@gmail.com"
location: "Cebu, Philippines"
phone: "+(63) 932-763-5395"
tel: "tel:+639327635395"
url: "http://iamkaye.github.io"

# Build settings
markdown: kramdown

# SASS settings
sass:
    style: :compressed